// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByeljFrShxsNhtcwLIm4DNIoTwIOiZErQ',
    appId: '1:389243523199:web:df50825c917ee464482f4a',
    messagingSenderId: '389243523199',
    projectId: 'historyio-ee042',
    authDomain: 'historyio-ee042.firebaseapp.com',
    storageBucket: 'historyio-ee042.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5lowXMHFvR9xnPb4iYxoowVUZTH4B6Mo',
    appId: '1:389243523199:android:c69eb205bb4c8dc8482f4a',
    messagingSenderId: '389243523199',
    projectId: 'historyio-ee042',
    storageBucket: 'historyio-ee042.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjovH2zG7esmVnGUFEhDUT9OUFUJ12Az4',
    appId: '1:389243523199:ios:8ad0e9e8ed32958f482f4a',
    messagingSenderId: '389243523199',
    projectId: 'historyio-ee042',
    storageBucket: 'historyio-ee042.firebasestorage.app',
    iosBundleId: 'com.example.aula',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjovH2zG7esmVnGUFEhDUT9OUFUJ12Az4',
    appId: '1:389243523199:ios:8ad0e9e8ed32958f482f4a',
    messagingSenderId: '389243523199',
    projectId: 'historyio-ee042',
    storageBucket: 'historyio-ee042.firebasestorage.app',
    iosBundleId: 'com.example.aula',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByeljFrShxsNhtcwLIm4DNIoTwIOiZErQ',
    appId: '1:389243523199:web:50f9e966a84fd6b9482f4a',
    messagingSenderId: '389243523199',
    projectId: 'historyio-ee042',
    authDomain: 'historyio-ee042.firebaseapp.com',
    storageBucket: 'historyio-ee042.firebasestorage.app',
  );
}
